Выполнено домашнее задание 5
Romanhardy99/CSharpEducation pull request #2
Opened 2024-09-24 11:49 UTC by Romanhardy99

курлык

2024-09-28 16:09 UTC, Dezodemius requested changes

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/Program.cs
> +
лишняя строка

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/Program.cs
> +
лишняя строка

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/User.cs
> +
лишняя строка

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/User.cs
> +    /// Класс для представления пользователя в системе управления пользователями.
Да просто `Пользователь`

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/User.cs
> +        /// Получает или устанавливает идентификатор пользователя.
Просто `Идентификатор пользователя`

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/User.cs
> +        #region Конструктор
`Конструкторы`

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/User.cs
> +        /// Инициализирует новый экземпляр пользователя с заданным id, именем и почтой.
`Конструктор`

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/User.cs
> +
Можно не разделять их пустыми строками

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/UserAlreadyExistsException.cs
> +        : base(message) { }
отступа не хватает

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/UserManager.cs
> +        List<User> users = new List<User>();
`private` и дока нужна

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/UserManager.cs
> +        /// Добавляет пользователя в список.
`Добавить пользователя`

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/UserManager.cs
> +                throw new UserAlreadyExistsException("Пользователь с таким id существует.");
можно ещё прям написать этот ID в исключении

2024-09-28 16:09 UTC, Dezodemius commented on HomeTask5/UserManager.cs
> +        /// Поиск пользователя по id
`Получить пользователя по ID`

2024-09-29 05:56 UTC, Romanhardy99 commented on HomeTask5/Program.cs
> +
удалил

2024-09-29 05:56 UTC, Romanhardy99 commented on HomeTask5/Program.cs
> +
удалил

2024-09-29 05:56 UTC, Romanhardy99 commented on HomeTask5/User.cs
> +
Удалил

2024-09-29 05:57 UTC, Romanhardy99 commented on HomeTask5/User.cs
> +    /// Класс для представления пользователя в системе управления пользователями.
Исправил

2024-09-29 05:57 UTC, Romanhardy99 commented on HomeTask5/User.cs
> +        /// Получает или устанавливает идентификатор пользователя.
Исправил

2024-09-29 05:57 UTC, Romanhardy99 commented on HomeTask5/UserAlreadyExistsException.cs
> +        : base(message) { }
Добавил

2024-09-29 05:57 UTC, Romanhardy99 commented on HomeTask5/UserManager.cs
> +        List<User> users = new List<User>();
Добавил

2024-09-29 05:57 UTC, Romanhardy99 commented on HomeTask5/UserManager.cs
> +        /// Добавляет пользователя в список.
Изменил

2024-09-29 05:57 UTC, Romanhardy99 commented on HomeTask5/UserManager.cs
> +                throw new UserAlreadyExistsException("Пользователь с таким id существует.");
Добавил

2024-09-29 05:57 UTC, Romanhardy99 commented on HomeTask5/UserManager.cs
> +        /// Поиск пользователя по id
Изменил

2024-09-30 19:55 UTC, Dezodemius approved these changes

2024-10-01 05:48 UTC, merged